# Generated by Django 5.0.2 on 2024-02-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='media/profile_pics/default_profile_picture.png', upload_to='profile_pics/'),
        ),
    ]
