# Generated by Django 5.0.2 on 2024-02-24 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
